name: Update gist with WakaTime stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: d4fac355a684526684cd8c4f9befa8ef
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - name: Keepalive Workflow
        uses: liskin/gh-workflow-keepalive@v1
